import './globals.css'
import NavBar from './components/NavBar'
import ContactSection from './components/ContactSection'
import DetailSection from './components/DetailSection'


export const metadata = {
  title: 'Hero Page',
  description: 'Generated by create next app, made by terlinko',
  icons: {
    icon: "/favicon.ico"
  },
}


export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <NavBar />
          <div className='mt-16 min-h-screen'>
            {children}
          </div>
          <footer className='p-4 bg-gray-950 text-white'>
            <ContactSection />
            <DetailSection />
          </footer>
      </body>
    </html>
  )
}
